apiVersion: v1
kind: Service
metadata:
  name: categories-service
  namespace: tasknotes
spec:
  type: ClusterIP
  selector:
    app: categories-service
  ports:
    - name: http
      port: 8006
      targetPort: 8006