apiVersion: v1
kind: Service
metadata:
  name: frontend-micro
  namespace: tasknotes
spec:
  type: NodePort
  selector:
    app: frontend-micro
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080