apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontends-ingress
  namespace: tasknotes
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: gateway-tls-secret
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-ssr
                port:
                  number: 3000
          - path: /micro
            pathType: Prefix
            backend:
              service:
                name: frontend-micro
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8083
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8083
