apiVersion: v1
kind: Service
metadata:
  name: tags-service
  namespace: tasknotes
spec:
  type: ClusterIP
  selector:
    app: tags-service
  ports:
    - name: http
      port: 8005
      targetPort: 8005