apiVersion: v1
kind: Service
metadata:
  name: gamification-service
  labels:
    app: gamification-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: gamification-service
  ports:
  - name: http
    port: 8003
    targetPort: 8003
    protocol: TCP
