apiVersion: v1
kind: Secret
metadata:
  name: cloudinary-secret
  labels:
    app: retofit
type: Opaque
stringData:
  CLOUDINARY_CLOUD_NAME: "dpsncmfxz"
  CLOUDINARY_API_KEY: "848674259162179"
  CLOUDINARY_API_SECRET: "6zQbbB8L-cZQbKT1MLIkuKKuqFg"
