apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  labels:
    app: retofit
type: Opaque
stringData:
  AUTH_DB_URL: "postgresql://postgres:Retofit2025@retofit.cd66iick6o60.us-east-2.rds.amazonaws.com:5432/retofit_auth"
  USERS_DB_URL: "postgresql://postgres:Retofit2025@retofit.cd66iick6o60.us-east-2.rds.amazonaws.com:5432/retofit_users"
  ACTIVITIES_DB_URL: "postgresql://postgres:Retofit2025@retofit.cd66iick6o60.us-east-2.rds.amazonaws.com:5432/retofit_activities"
  POSTS_DB_URL: "postgresql://postgres:Retofit2025@retofit.cd66iick6o60.us-east-2.rds.amazonaws.com:5432/retofit_posts?sslmode=no-verify"
  ADMIN_DB_URL: "postgresql://postgres:Retofit2025@retofit.cd66iick6o60.us-east-2.rds.amazonaws.com:5432/retofit_retos"
