apiVersion: v1
kind: Secret
metadata:
  name: firebase-secret
  labels:
    app: retofit
type: Opaque
stringData:
  FIREBASE_API_KEY: "AIzaSyBahlztUM-HxBN5chRXm4bg3_tfac327qc"
  FIREBASE_AUTH_DOMAIN: "retofit-65d7f.firebaseapp.com"
  FIREBASE_PROJECT_ID: "retofit-65d7f"
  FIREBASE_STORAGE_BUCKET: "retofit-65d7f.firebasestorage.app"
  FIREBASE_MESSAGING_SENDER_ID: "84767435359"
  FIREBASE_APP_ID: "1:84767435359:web:fd2e56a651adb79d0e89ea"
  FIREBASE_MEASUREMENT_ID: "G-1P33Y9WDD2"
