apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  labels:
    app: retofit
type: Opaque
stringData:
  SECRET_KEY: "f40cf292b97e6ec1e40e6a376e035ee9ebd9369c9dc233c474216ec0fe1b54aa"
  ALGORITHM: "HS256"
