apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: retofit
type: Opaque
stringData:
  MONGO_URL: "mongodb://mongo:wMssbdHQqDrJaPwUGqtqyfoqmPHvneJZ@gondola.proxy.rlwy.net:10201/retofit_gamification?authSource=admin"
