apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
  labels:
    app: retofit
type: Opaque
stringData:
  MAIL_SERVER: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USERNAME: "retofitapp@gmail.com"
  MAIL_PASSWORD: "ubid jqul mzmg nnwh"
  MAIL_FROM: "retofitapp@gmail.com"
  MAIL_USE_TLS: "true"
  MAIL_USE_SSL: "false"
