apiVersion: apps/v1
kind: Deployment
metadata:
  name: categories-service
  namespace: tasknotes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: categories-service
  template:
    metadata:
      labels:
        app: categories-service
    spec:
      containers:
        - name: categories-service
          image: 602223305716.dkr.ecr.us-east-1.amazonaws.com/categories-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8006
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8006"
            - name: POSTGRES_CONNECTION
              value: Host=postgres-categories;Port=5432;Database=tasknotes_categories_dotnet;Username=postgres;Password=postgres
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8006
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8006
            initialDelaySeconds: 20
            periodSeconds: 20