apiVersion: v1
kind: Service
metadata:
  name: frontend-ssr
  namespace: tasknotes
spec:
  type: NodePort
  selector:
    app: frontend-ssr
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30030