apiVersion: v1
kind: Service
metadata:
  name: mongo-logs
  namespace: tasknotes
spec:
  type: ClusterIP
  selector:
    app: mongo-logs
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
