apiVersion: v1
kind: Service
metadata:
  name: postgres-userprofile
  namespace: tasknotes
spec:
  type: ClusterIP
  selector:
    app: postgres-userprofile
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432