apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: tasknotes
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: api-gateway
        metrics_path: /metrics
        static_configs:
          - targets: ['api-gateway:8083']
      - job_name: search-service
        metrics_path: /metrics
        static_configs:
          - targets: ['search-service:8008']
