apiVersion: v1
kind: Secret
metadata:
  name: postgres-categories-credentials
  namespace: tasknotes
type: Opaque
stringData:
  POSTGRES_DB: tasknotes_categories_dotnet
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres