apiVersion: v1
kind: Service
metadata:
  name: user-profile-service
  namespace: tasknotes
spec:
  type: ClusterIP
  selector:
    app: user-profile-service
  ports:
    - name: http
      port: 8007
      targetPort: 8007