apiVersion: 1

datasources:
  - name: InfluxDB
    uid: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    user: tasknotes
    secureJsonData:
      password: changeme
    jsonData:
      httpMode: POST
      version: InfluxQL
    isDefault: false
    editable: true