apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: userservice-hpa
  namespace: musicshare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userservice
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: musicservice-hpa
  namespace: musicshare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: musicservice
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: socialservice-hpa
  namespace: musicshare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: social-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 55
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notificationservice-hpa
  namespace: musicshare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notificationservice
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
