apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - databases.yaml
  - mongodb.yaml
  - backend-deployments-services.yaml
  - frontend-deployment-service.yaml
  - ingress.yaml
  - hpa.yaml
  - frontend-config.yaml
  - cert-manager-issuer.yaml
  - spotify-secret.yaml
  - userservice-secret.yaml
  - postgres-init-config.yaml
