apiVersion: v1
kind: Secret
metadata:
  name: spotify-credentials
  namespace: musicshare
type: Opaque
stringData:
  spotify_client_id: "TU_CLIENT_ID_DE_SPOTIFY_AQUI"
  spotify_client_secret: "TU_CLIENT_SECRET_DE_SPOTIFY_AQUI"
