apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: activities-to-users-grpc
  labels:
    app: retofit
spec:
  podSelector:
    matchLabels:
      app: activities-service
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: users-service
    ports:
    - protocol: TCP
      port: 50051  # gRPC port
